=begin
#Triglav API

#Triglav API Reference

OpenAPI spec version: 1.0.0
Contact: triglav_admin_my@dena.jp
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClient::ClustersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClustersApi' do
  before do
    # run before each test
    @instance = TriglavClient::ClustersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClustersApi' do
    it 'should create an instact of ClustersApi' do
      expect(@instance).to be_instance_of(TriglavClient::ClustersApi)
    end
  end

  # unit tests for create_cluster
  # 
  # Creates a new cluster
  # @param cluster Cluster to add
  # @param [Hash] opts the optional parameters
  # @return [ClusterResponse]
  describe 'create_cluster test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_cluster
  # 
  # Deletes single cluster
  # @param id_or_name ID or Name of cluster to fetch
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_cluster test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_cluster
  # 
  # Returns a single cluster
  # @param id_or_name ID or Name of cluster to fetch
  # @param [Hash] opts the optional parameters
  # @return [ClusterResponse]
  describe 'get_cluster test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_clusters
  # 
  # Returns all clusters from the system
  # @param [Hash] opts the optional parameters
  # @return [Array<ClusterEachResponse>]
  describe 'list_clusters test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_cluster
  # 
  # Updates a single cluster
  # @param id_or_name ID or Name of cluster to fetch
  # @param cluster Cluster parameters to update
  # @param [Hash] opts the optional parameters
  # @return [ClusterResponse]
  describe 'update_cluster test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
