=begin
#Triglav API

#Triglav API Reference

OpenAPI spec version: 1.0.0
Contact: triglav_admin_my@dena.jp
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClient::JobsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @instance = TriglavClient::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instact of JobsApi' do
      expect(@instance).to be_instance_of(TriglavClient::JobsApi)
    end
  end

  # unit tests for create_or_update_job
  # 
  # Creates or Updates a single job
  # @param job Job parameters
  # @param [Hash] opts the optional parameters
  # @return [JobResponse]
  describe 'create_or_update_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_job
  # 
  # Deletes single job
  # @param id_or_uri ID or URI of job to fetch
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_job
  # 
  # Returns a single job
  # @param id_or_uri ID or URI of job to fetch
  # @param [Hash] opts the optional parameters
  # @return [JobResponse]
  describe 'get_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_jobs
  # 
  # Returns all jobs
  # @param [Hash] opts the optional parameters
  # @return [Array<JobEachResponse>]
  describe 'list_jobs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
