=begin
#Triglav

#Triglav API Reference.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClientBase::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = TriglavClientBase::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instact of UsersApi' do
      expect(@instance).to be_instance_of(TriglavClientBase::UsersApi)
    end
  end

  # unit tests for api_v1_users_create
  # Creates a new User
  # 
  # @param name Name
  # @param authenticator local or ldap.dena.local
  # @param groups Groups
  # @param password Password
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description Description
  # @option opts [String] :email Email
  # @return [nil]
  describe 'api_v1_users_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_users_destroy
  # Deletes an existing User item
  # 
  # @param id User Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_users_destroy test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_users_index
  # Fetches all User items
  # This lists all the active users
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_users_index test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_users_show
  # Fetches a single User item
  # 
  # @param id User Id
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'api_v1_users_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_users_update
  # Updates an existing User
  # 
  # @param id User Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name Name
  # @option opts [String] :description Description
  # @option opts [String] :authenticator Local or ldap
  # @option opts [String] :email Email
  # @option opts [Array<Object>] :groups Groups
  # @option opts [String] :password Password for local authentication
  # @return [nil]
  describe 'api_v1_users_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
