=begin
#Triglav

#Triglav API Reference.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClientBase::ClustersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClustersApi' do
  before do
    # run before each test
    @instance = TriglavClientBase::ClustersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClustersApi' do
    it 'should create an instact of ClustersApi' do
      expect(@instance).to be_instance_of(TriglavClientBase::ClustersApi)
    end
  end

  # unit tests for api_v1_clusters_create
  # Creates a new Cluster
  # 
  # @param name Name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description Description
  # @return [nil]
  describe 'api_v1_clusters_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_clusters_destroy
  # Deletes an existing Cluster item
  # 
  # @param id Cluster Id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_clusters_destroy test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_clusters_index
  # Fetches all Cluster items
  # This lists all clusters
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_clusters_index test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_clusters_show
  # Fetches a single Cluster item
  # 
  # @param id Cluster Id
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'api_v1_clusters_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_clusters_update
  # Updates an existing Cluster
  # 
  # @param id Cluster Id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name Name
  # @option opts [String] :description Description
  # @return [nil]
  describe 'api_v1_clusters_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
