=begin
#Triglav API

#Triglav API Reference

OpenAPI spec version: 1.0.0
Contact: triglav_admin_my@dena.jp
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClientBase::ClusterApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClusterApi' do
  before do
    # run before each test
    @instance = TriglavClientBase::ClusterApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClusterApi' do
    it 'should create an instact of ClusterApi' do
      expect(@instance).to be_instance_of(TriglavClientBase::ClusterApi)
    end
  end

  # unit tests for add_cluster
  # 
  # Creates a new cluster
  # @param cluster Cluster to add
  # @param [Hash] opts the optional parameters
  # @return [Cluster]
  describe 'add_cluster test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_cluster_by_id_or_name
  # 
  # Deletes single cluster
  # @param id_or_name ID or Name of cluster to fetch
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_cluster_by_id_or_name test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_cluster_by_id_or_name
  # 
  # Returns a single cluster
  # @param id_or_name ID or Name of cluster to fetch
  # @param [Hash] opts the optional parameters
  # @return [Cluster]
  describe 'find_cluster_by_id_or_name test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_clusters
  # 
  # Returns all clusters from the system
  # @param [Hash] opts the optional parameters
  # @return [Array<ClusterEach>]
  describe 'find_clusters test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_cluster_by_id_or_name
  # 
  # Updates a single cluster
  # @param id_or_name ID or Name of cluster to fetch
  # @param cluster Cluster parameters to update
  # @param [Hash] opts the optional parameters
  # @return [Cluster]
  describe 'update_cluster_by_id_or_name test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
