=begin
#Triglav API

#Triglav API Reference

OpenAPI spec version: 1.0.0
Contact: triglav_admin_my@dena.jp
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClientBase::JobApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JobApi' do
  before do
    # run before each test
    @instance = TriglavClientBase::JobApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobApi' do
    it 'should create an instact of JobApi' do
      expect(@instance).to be_instance_of(TriglavClientBase::JobApi)
    end
  end

  # unit tests for create_or_update_job
  # 
  # Creates or Updates a single job
  # @param job Job parameters
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'create_or_update_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_job_by_id_or_uri
  # 
  # Deletes single job
  # @param id_or_uri ID or URI of job to fetch
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_job_by_id_or_uri test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_job_by_id_or_uri
  # 
  # Returns a single job
  # @param id_or_uri ID or URI of job to fetch
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'find_job_by_id_or_uri test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_jobs
  # 
  # Returns all jobs
  # @param [Hash] opts the optional parameters
  # @return [Array<JobEach>]
  describe 'find_jobs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
