=begin
#Triglav

#Triglav API Reference.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for TriglavClientBase::JobsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @instance = TriglavClientBase::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instact of JobsApi' do
      expect(@instance).to be_instance_of(TriglavClientBase::JobsApi)
    end
  end

  # unit tests for api_v1_jobs_destroy
  # Deletes an existing Job item
  # 
  # @param id_or_uri Resource Id or URI
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_jobs_destroy test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_jobs_show
  # Fetches a single Job
  # 
  # @param id_or_uri Resource Id or URI
  # @param [Hash] opts the optional parameters
  # @return [Resource]
  describe 'api_v1_jobs_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_jobs_update
  # Creates or Updates a Job
  # Input and output resources are also created if they do not exist. Use Resource API to update.
  # @param uri Job URI
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Object>] :input_resources Input Resources
  # @option opts [Array<Object>] :output_resources Output Resources
  # @return [nil]
  describe 'api_v1_jobs_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
